### ISSUE TITLE
Crashes when editing if the edited number is equal to another number in the list

### ISSUE THREAD

**Issue by QuestofIranon** [qguv/NoPhoneSpam#1]
The app will crash if you edit a phone number and is the same as another number on the list. It's not a typical use case but I found it when I was editing a number to include a wild card and it matched another wildcard number I had set up previously.

I tested adding new numbers that already exist and in that case it will just not add the number.

**Comment by qguv** [comment]
Thanks for the report! This is actually a fork of the original code with a patch I proposed to upstream. I think this is likely an upstream bug. Would you [file it with them](https://gitlab.com/bitfireAT/NoPhoneSpam/issues/new)? Thanks!

**Comment by qguv** [comment]
If you don't have a Gitlab account, I can file it for you.
